remote_theme: mmistakes/minimal-mistakes

title: "Universal Dashboard"
description: "Universal Dashboard is a cross-platform PowerShell module for developing and hosting web-based, interactive dashboards."
url: "https://universaldashboard.io"
repository: "ironmansoftware/universaldashboard.io"

include:
  - _pages

og_image                 : "/assets/images/UDLogo.png"

analytics:
  provider               : "google" 
  google:
    tracking_id          : "UA-8902901-11"

author:
  name             : "Adam Driscoll"
  avatar           : ""
  bio              : ""
  location         : ""
  email            :
  uri              : "https://universaldashboard.io"
  home             : "https://universaldashboard.io"
  bitbucket        :
  codepen          :
  dribbble         :
  flickr           :
  facebook         :
  foursquare       :
  github           : "ironmansoftware"
  gitlab           :
  google_plus      :
  keybase          :
  instagram        :
  lastfm           :
  linkedin         :
  pinterest        :
  soundcloud       :
  stackoverflow    : # https://stackoverflow.com/users/123456/username
  steam            :
  tumblr           :
  twitter          : "adamdriscoll"
  vine             :
  weibo            :
  xing             :
  youtube          :
  
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache
